import React from 'react';
import { LayoutContainer, Main } from './Layout.style';
import Head from 'next/head';
import SideNav from './SideNav';
import TopBar from './TopBar';

type Props = {
  children: JSX.Element;
};

const Layout = ({ children }: Props) => {
  return (
    <LayoutContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <div className="contents">
        <SideNav />
        <Main>{children}</Main>
      </div>
    </LayoutContainer>
  );
};

export default Layout;
